### ISSUE TITLE
执行yarn dev提示 ERROR  run failed: We did not detect an in-use package manager for your project. 

### ISSUE THREAD

**Issue by seamanm** [TangSengDaoDao/TangSengDaoDaoWeb#1]
mac os 13.5 (22G74)
CPU Apple M1 Pro

(base)  TangSengDaoDaoWeb % yarn dev
 ERROR  run failed: We did not detect an in-use package manager for your project. Please set the "packageManager" property in your root package.json (https://nodejs.org/api/packages.html#packagemanager) or run `npx @turbo/codemod add-package-manager` in the root of your monorepo.
(base)  TangSengDaoDaoWeb % npx @turbo/codemod add-package-manager
Thank you for using @turbo/codemod!

But before we continue, please stash or commit your git changes.

You may use the --force flag to override this safety check.
(base)TangSengDaoDaoWeb % yarn dev
 ERROR  run failed: We did not detect an in-use package manager for your project. Please set the "packageManager" property in your root package.json (https://nodejs.org/api/packages.html#packagemanager) or run `npx @turbo/codemod add-package-manager` in the root of your monorepo.
(base)  TangSengDaoDaoWeb %

**Comment by tangtaoit** [comment]
node版本使用v16 npm使用8.19试试
