### ISSUE TITLE
web端上传图片报错

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoWeb#10]
在web端聊天发图片上传失败
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/64d8ab6d-6548-4fd8-936a-b52c16357a06)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/b749ab06-1479-4d2f-bbdf-abe9b095f2ca)

查看日志：
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/643010f1-8c80-4c24-8c16-cfdfc940b3cf)
tsdd-tangsengdaodaoserver-1   | {"level":"error","time":"2023-10-16 13:48:54","msg":"【File】检测 chat目录是否存在错误"}
tsdd-tangsengdaodaoserver-1   | {"level":"error","time":"2023-10-16 13:48:54","msg":"【File】上传文件失败！","error":"Get \"https://10.30.0.23/chat/?location=\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
tsdd-tangsengdaodaoserver-1   | [GIN] 2023/10/16 - 13:48:54 | 400 |   52.627695ms |    192.168.65.1 | POST     "/v1/file/upload?type=chat&path=/1/9a302040e4f94e049b817fe3ebed3ebf/C18CB513E9F17ADCB9BB5220F5197E86"
tsdd-wukongim-1               | {"level":"debug","time":"2023-10-16 13:49:43","msg":"【Processor】ping","conn":"Conn[2] uid=5fde0c3719824e858d8b12453340a56b fd={70} deviceFlag=WEB deviceLevel=Slave deviceID=65c6ee9fc8618f8d481fac081228ab9bW"}

**Comment by tangtaoit** [comment]
这个错误看上去是你的https证书配置错了

**Comment by echo-music** [comment]
> 这个错误看上去是你的https证书配置错了

证书是正常的
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/0c102a7b-6743-4a43-aa01-eb8480f747c3)
上传走的接口也是https,但是
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/84e07470-d6e5-48c8-a22e-e673f76f6016)
这个接口我看页面也没有请求啊，是不是后台上传的时候请求改接口呢？

**Comment by tangtaoit** [comment]
配置里的minio上传地址应该配置错了，应该是minio的地址，你这里配置的api的地址。如果对minio不了解的话 可以参考下他们的官方文档

**Comment by echo-music** [comment]
解决了，谢谢
