### ISSUE TITLE
拉最新代码运行报错

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoWeb#13]
拉取main 分支代码运行访问就报错了，如何忽略这个错误呢？
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/3264291e-55f6-4472-84a0-3032de9cde8f)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/a53c1b3d-e06a-4244-8960-0ce089710bf0)

**Comment by tangtaoit** [comment]
![72101698740130_ pic](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/3895878/377b8cdc-bcee-4b49-b6f9-a4736ff91e55)

注释掉这里即可

**Comment by echo-music** [comment]
> ![72101698740130_ pic](https://user-images.githubusercontent.com/3895878/279332798-377b8cdc-bcee-4b49-b6f9-a4736ff91e55.jpg)
> 
> 注释掉这里即可

谢谢，解决了
