### ISSUE TITLE
源码运行点击好友聊天报错

### ISSUE THREAD

**Issue by 007-sys** [TangSengDaoDao/TangSengDaoDaoWeb#16]
源码部署时 点击好友进入聊天窗口报错

系统环境：Mac m1 

TangSengDaoDaoWeb 
步骤
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/16251271/eff8d5f4-ae87-410c-b022-9c57a4f3828e)

![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/16251271/77ddac42-6e54-4a58-af7e-20d60d20dfeb)

**Comment by budou0608** [comment]
已经修复，点击好友聊天报错
