### ISSUE TITLE
使用tauri 打包的pc wind7程序，会出现多个已经登录了的窗口,怎么解决

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoWeb#19]
使用tauri 打包的pc wind7程序，
第一次登陆成功后，再次双击打开程序，又弹出新的窗口，会出现多个已经登陆的窗口

<img width="1519" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/302710d1-e432-4288-bf6c-c498a46ccd8e">

**Comment by budou0608** [comment]
请使用electron版本重新打包
