### ISSUE TITLE
调试模式下正常运行，打包成exe运行则出现未知错误

### ISSUE THREAD

**Issue by 422557374** [TangSengDaoDao/TangSengDaoDaoWeb#2]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/69720910/0eae7607-9cd6-46d0-a4a3-655fb91c5378)

**Comment by tangtaoit** [comment]
打包需要https

**Comment by 422557374** [comment]
> 资源需要https

是不是全部资源(比如 5100 5200这些 )全部需要换成https才能正常使用，打包出来的exe  ，apiURL 换成https后可以实现正常登录，登录进去则显示已断开的状态
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/69720910/25966334-e495-4144-ba71-d2f56884e5da)

**Comment by tangtaoit** [comment]
长连接需要wss
