### ISSUE TITLE
用你们docker部署的服务，在前台用浏览器打开出现两个截频按钮

### ISSUE THREAD

**Issue by zhaofeng1949** [TangSengDaoDao/TangSengDaoDaoWeb#26]
用你们docker部署的服务，在前台用浏览器打开出现两个截频按钮
![微信截图_20240430142711](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/85348408/87a92439-3b17-48ff-9985-7a05e05fe9b4)

**Comment by tangtaoit** [comment]
已修复
