### ISSUE TITLE
使用yarn run build-ele:win命令打包完以后，打开pc端应用软件出现白屏，不能正常使用

### ISSUE THREAD

**Issue by zhaofeng1949** [TangSengDaoDao/TangSengDaoDaoWeb#27]
使用yarn run build-ele:win命令打包完以后，打开pc端应用软件出现白屏，不能正常使用
![微信图片_20240430143003](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/85348408/36301406-54d2-48a8-9bae-f93102fe455f)

**Comment by budou0608** [comment]
执行`yarn run build-ele:win`，先执行`yarn build`进行编译命令，在打包对应的桌面应用
