### ISSUE TITLE
web/pc端希望增加一个可以发送截图以及图片文件的功能

### ISSUE THREAD

**Issue by 422557374** [TangSengDaoDao/TangSengDaoDaoWeb#3]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/69720910/764a2a95-9dfa-4372-848f-19b64f044516)

**Comment by tangtaoit** [comment]
采用QQ截图或其他截图软件， 然后回到web ctrl + v 即可发送

**Comment by 422557374** [comment]
> 使用QQ截图或其他截图软件，然后返回web ctrl + v 即可发送

你好，使用QQ截图后，在其他软件上可以粘贴出截图，回到web端， ctrl + v 没反应。  然后测试web端拖动图片到聊天窗口，会提示发送给某某，实际上也没反应。
