### ISSUE TITLE
发送文件或图片时  在消息对队列中出现空白消息的情况

### ISSUE THREAD

**Issue by cxw-wxsr** [TangSengDaoDao/TangSengDaoDaoWeb#30]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/59679486/7470be42-e74a-4faa-a4a8-a2805c7aee7c)
在发送图片或者文件时  要是遇到网络不好的情况导致WebSocket断开  后面重连成功过后 会重新发送消息  这个时候消息成功发出，但是在/message/channel/sync接口返回的信息中url字段是空值

**Comment by budou0608** [comment]
最新代码，试一下，看看还有这个问题不

**Comment by wangwenfan** [comment]
还是有这个问题，但出现频率要低一点了
