### ISSUE TITLE
图片上传的时候发送图片消息的时候url参数是什么时候赋值的没找到

### ISSUE THREAD

**Issue by zyh819heng** [TangSengDaoDao/TangSengDaoDaoWeb#32]
图片上传的时候发送图片消息的时候url参数是什么时候赋值的没找到 大佬可以解惑一下吗

**Comment by zyh819heng** [comment]
![1721033249753](https://github.com/user-attachments/assets/0e987227-a826-4aba-b594-c1d86b78738f)
这个的地方初始化img消息的时候是没传url的previewUrl是一个base64的东西

**Comment by zyh819heng** [comment]
![12aac063bb175ae17c911adea5df2be](https://github.com/user-attachments/assets/33baf499-7a90-4b09-a38f-990c2e7c1ad7)
![c87f56e822b409ee577f3f4c221efca](https://github.com/user-attachments/assets/00c5441f-ca67-4b38-ab4c-e9909ab2ccaf)
看起来像是sendMessage里面对img消息进行的操作 但是点进去发现也没有

**Comment by tangtaoit** [comment]
> ![1721033249753](https://private-user-images.githubusercontent.com/22977205/348646565-0e987227-a826-4aba-b594-c1d86b78738f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzM3NzQsIm5iZiI6MTcyMTAzMzQ3NCwicGF0aCI6Ii8yMjk3NzIwNS8zNDg2NDY1NjUtMGU5ODcyMjctYTgyNi00YWJhLWI1OTQtYzFkODZiNzg3MzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4NTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YjJkM2ZkMjg5MzdiZmM0OGRjOTQ5ZDQxYmMzMmJiYjhjNTFkZTYzYmI4ZDk0Mjk2ZTI3NTljZDFjNGNmYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uVaHqC3Dvt7vULXESNQ7-BjxaPpyZt7gn0JMHBHjOsY) 这个的地方初始化img消息的时候是没传url的previewUrl是一个base64的东西

file和imgData 只需要一个有值即可

**Comment by tangtaoit** [comment]
remoteUrl是在上传任务中被赋值的。 https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/blob/main/packages/tsdaodaodatasource/src/task.ts#L70

<img width="876" alt="image" src="https://github.com/user-attachments/assets/0ab29dfd-c653-4500-bb18-c499df27d044">
