### ISSUE TITLE
Web端收到的好友申请无法拒绝或清除通知，在其他端清理过好友申请通知，在web端还能被看到

### ISSUE THREAD

**Issue by baishuijianjia** [TangSengDaoDao/TangSengDaoDaoWeb#33]
![屏幕截图 2024-07-21 155239](https://github.com/user-attachments/assets/2e67fad4-ebbb-4141-9a5c-dc964af6cafe)
如图所示，只有接受按钮，没有拒绝或忽略

**Comment by budou0608** [comment]
已经修复
