### ISSUE TITLE
【Mac、Win端】创建群聊的时候，被邀请人的备注没有展示，显示的还是昵称（附图）

### ISSUE THREAD

**Issue by zhangxiaozhe8023** [TangSengDaoDao/TangSengDaoDaoWeb#34]
【步骤】
点击 **发起群聊**查看好友列表，展示的都是原始昵称
【期望结果】
点击 **发起群聊**查看好友列表，有备注的展示备注，没有备注的展示原始昵称
<img width="960" alt="image" src="https://github.com/user-attachments/assets/589f546e-4b35-4bad-97e9-9b3b9e1915f6">

**Comment by budou0608** [comment]
已修复
