### ISSUE TITLE
【Mac、Win版本】发起群聊的时候，已在群聊里面了，期望不能再次选择并且邀请进群（附图）

### ISSUE THREAD

**Issue by zhangxiaozhe8023** [TangSengDaoDao/TangSengDaoDaoWeb#35]
**步骤：**
群聊已邀请了用户A，再次邀请用户A，还能选中再次邀请
**期望结果：**
群聊已邀请了用户A，再次邀请用户A，不能选中或者在被邀请列表移除
<img width="960" alt="image" src="https://github.com/user-attachments/assets/402238dc-4bfa-49cc-838d-28fb0c886613">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/73a17c73-6738-4bef-931e-f5041b34aeb7">

**Comment by budou0608** [comment]
已修复
