### ISSUE TITLE
能加一下web/pc的本地存储吗

### ISSUE THREAD

**Issue by zyh819heng** [TangSengDaoDao/TangSengDaoDaoWeb#38]
增加web/pc的本地消息存储可以让服务器压力小一点流量扣的少一点（切换不同聊天窗口也能快一些往上翻页也能快一些），不然用户每次切换聊天窗口都要请求消息同步服务器流量消耗大

**Comment by tangtaoit** [comment]
pc/web一般网络流畅，WuKongIM的接口是<毫秒级别的, 考虑几下几点不做本地存储。 app端有做本地存储。
