### ISSUE TITLE
windowd打包exe有问题

### ISSUE THREAD

**Issue by cuichangle** [TangSengDaoDao/TangSengDaoDaoWeb#40]
node 版本 18.17.1
yarn 版本 1.22.19
问题描述：Mac端打包没有问题，
如果在外面执行yarn build-ele:Win
报错如下

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.78s
Failed:    @tsdaodao/web#build-ele:win

 ERROR  run failed: command  exited (1)

如果apps/web下打包，报错信息如下：
const wrap = require('wrap-ansi');
             ^
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\project\TangSengDaoDaoWeb-main\node_modules\wrap-ansi\index.js from D:\project\TangSengDaoDaoWeb-main\node_modules\cliui\build\index.cjs not supported.
![微信截图_20240920180050](https://github.com/user-attachments/assets/98dd0de8-ee51-492c-b427-f0eedc9faa62)
![error7](https://github.com/user-attachments/assets/8436efb2-65ce-43aa-a2ba-d97752e6d47f)

**Comment by budou0608** [comment]
问题已经修复，重新拉一下代码。
如果webpack运行比较慢可以使用rspack，在dev-rspack分支。
建议使用**dev-rspack**分支
