### ISSUE TITLE
web端想兼容低版本chrom安装第三方包报一直报错（能兼容吗）

### ISSUE THREAD

**Issue by qiuhong1** [TangSengDaoDao/TangSengDaoDaoWeb#46]
![微信截图_20241122103335](https://github.com/user-attachments/assets/6bf1b9df-9cb3-4404-834f-4893d6bb0c8d)

**Comment by tangtaoit** [comment]
在项目根目录下执行，使用yarn

**Comment by qiuhong1** [comment]
有没有什么适配低版本的工具呢 我用babel-polyfill还是不行呢
![微信图片_20241122152209](https://github.com/user-attachments/assets/caaf4b82-94bb-4f68-b424-ef3147cadfd0)

**Comment by tangtaoit** [comment]
你这是有多低啊，这个只能你自己研究了。
