### ISSUE TITLE
v1.0.0 版本没有发图片功能

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoWeb#5]
您好，运行该v1.0.0 项目，没有发图片功能，看介绍里面是有的，还是说功能还没开发呢？

**Comment by tangtaoit** [comment]
运行最新的源码

**Comment by echo-music** [comment]
> 运行最新的源码

我尝试了一下，报错
im 服务版本是
Mode: debug
tsdd-tangsengdaodaoserver-1   | LLLLLLLLLL08@880CfLLLLLLLLLLLLLLLLLLLLLL   Config: configs/tsdd.yaml
tsdd-tangsengdaodaoserver-1   | LLLLLLLLfL8@8@@8LfLLLLLLLLLLLLLLLLLLLLLL   App name: 唐僧叨叨
tsdd-tangsengdaodaoserver-1   | ffffffffft0@@8@8ffffffffffffffffffffffff   Version: v1.0.4
tsdd-tangsengdaodaoserver-1   | fffffffffCCL8@GLLfLLLfffffffffffffffffff   Git: 1696315191-063b0b8d9d4dc68d66e2b452f93a538f18b6d18c
tsdd-tangsengdaodaoserver-1   | ffffffffCLLC0@GCCLLLLCffffffffffffffffff   Go build: go1.20.8
tsdd-tangsengdaodaoserver-1   | ffffffffG0@@@@@@@8Ltffffffffffffffffffff   IM URL: http://wukongim:5001
tsdd-tangsengdaodaoserver-1   | ffffffftC888888888Gtffffffffffffffffffff   File Service: minio
tsdd-tangsengdaodaoserver-1   | ffffffftttttttttttttffffffffffffffffffff   The API is listening at: :8090


下面是我切换main 分支拉取的最新代码，
yarn install
yarn run dev

点击进入群里，就报错了
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/d6a12043-6580-4e18-8945-4f2fc40b0a08)

这个是报错的原因：
xhr.js:210 GET http://127.0.0.1:8090/v1/sticker/user/category 404 (Not Found)
dispatchXhrRequest @ xhr.js:210
xhrAdapter @ xhr.js:15
dispatchRequest @ dispatchRequest.js:58
Promise.then (async)
request @ Axios.js:92
Axios.<computed> @ Axios.js:136
wrap @ bind.js:9
get @ APIClient.ts:66
userStickerCategory @ datasource.ts:164
requestStickerCategory @ index.tsx:118
componentDidMount @ index.tsx:113
commitLifeCycles @ react-dom.development.js:20663
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
index.html:1 Uncaught (in promise)

**Comment by tangtaoit** [comment]
这个错误是没表情商店模块导致的，可以忽略，这个群头像没显示检查下文件服务是否正确部署。

**Comment by echo-music** [comment]
> 这个错误是没表情商店模块导致的，可以忽略，这个群头像没显示检查下文件服务是否正确部署。

嗯嗯，.env 里面的 EXTERNAL_IP= 我配上127.0.0.1 所有没有显示头像，换成本机的内网地址就OK了。这个错误是没表情商店模块导致的，可以忽略 这个问题我再看看怎么解决吧，多谢您
