### ISSUE TITLE
在本地用docker-compose 部署的环境，在本地打包的mac 程序，自己本地可登陆，发给别人却登陆报错

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoWeb#6]
您好，遇到一个问题：

环境：im本地环境
安装包：mac 安装包

在同一网段，自己的电脑可登陆，用别人的电脑就登陆不上去了，直接报错
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/bec30e1d-4bcf-4032-9f6d-ebbbf65e6d1e)

但是在别人的电脑上，网页版登陆成功了，也可访问。这是什么原因呢？

**Comment by tangtaoit** [comment]
开发环境可以是http ，打包后的正式安装包，接口地址必须是https的才可以。所以才会出现你在开发模式下可以，打包后不行

**Comment by echo-music** [comment]
问题解决

**Comment by echo-music** [comment]
解决了
