### ISSUE TITLE
图片发送了，对端app 接收的是空的图片

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoWeb#8]
A 宿主机装了一个im客户端（mac）（在这台机子搭建的环境）
B 宿主机装了一个im客户端 (window) 
发现问题是：
1、图片只能发给自己看，对端接收的是空的图片
2、在客户端新建的朋友圈头像不展示，web端刷新才展示

![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/b1d676e9-7dd1-4093-969a-ff5debae6e2a)

![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/f37bc29b-7c3e-46df-9aa1-174114ab425f)

最终找到了图片不展示的原因：
因为我使用的是http+ssl 协议，所以发送图片的时候发现跳转地址http，app限制了http访问，所以发送图片，对端 im app显示是空的！
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/assets/5945928/c7655357-c00a-4629-8e3b-3ab52eb78ec8)
所以我的问题是跳转地址配置么？在哪里配置呢？

**Comment by tangtaoit** [comment]
图片会跳转到文件服务的地址，你文件服务在客户端（PC）下也需要https的才可以 配置查看：https://tsdaodao.com/dev/backend/fullconfig.html 的minio项

**Comment by echo-music** [comment]
> Refere

好的，解决了
